create table public."INPUT_出品詳細情報" (
  "出品者SKU" character varying(20)
  , "ASIN 1" character varying(20)
  , "商品名" character varying(500)
  , "商品の説明" character varying(2000)
  , "出品ID" character varying(20)
  , "価格" character varying(10)
  , "数量" character varying(10)
  , "出品日" character varying(30)
  , "商品IDタイプ" character varying(10)
  , "コンディション説明" character varying(500)
  , "コンディション" character varying(10)
  , "国外へ配送可" character varying(20)
  , "迅速な配送" character varying(20)
  , "商品ID" character varying(20)
  , "在庫数" character varying(10)
  , "フルフィルメント・チャンネル" character varying(20)
  , "使用しない支払い方法" character varying(20)
  , "配送日時指定SKUリスト" character varying(20)
  , "merchant-shipping-group" character varying(20)
  , "ポイント" character varying(10)
  , "商品税コード" character varying(20)
  , "調達タイプ" character varying(20)
  , "店舗名" character varying(20)
);
