create table public."INPUT_発送情報_AMAZON" (
  "発送状態" character varying(20)
  , "注文番号" character varying(50)
  , "注文項目番号" character varying(20)
  , "注文時間" character varying(50)
  , "支払時間" character varying(50)
  , "レポート時間" character varying(50)
  , "発送期限" character varying(50)
  , "残り日数" character varying(10)
  , "購入者メール" character varying(50)
  , "購入者名称" character varying(50)
  , "購入者電話番号" character varying(50)
  , "SKU番号" character varying(50)
  , "商品名称" character varying(500)
  , "商品数量" character varying(10)
  , "発送済数量" character varying(10)
  , "未発送数量" character varying(10)
  , "発送レベル" character varying(20)
  , "宛先名称" character varying(50)
  , "宛先住所１" character varying(200)
  , "宛先住所２" character varying(200)
  , "宛先住所３" character varying(200)
  , "宛先住所市" character varying(50)
  , "宛先都道府県" character varying(20)
  , "宛先郵便番号" character varying(20)
  , "宛先国" character varying(10)
);
