<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
    <div class="dialog" id="delivery_content_inputdialog" style="display:block;background-color: rgb(255,255,240);">
        <script>
            var delivery_content_inputdialog = null;
            $(function () {
                delivery_content_inputdialog = $("#delivery_content_inputdialog").dialog({
                    title: "納品内容",
                    autoOpen: false,
                    resizable: true,
                    height: 700,
                    width: 1137,
                    modal: true,
                    open: function () {
                        setTimeout(function () { });
                    },
                    close: function () {
                        setTimeout(function () { });
                    },
                });
            });
        </script>
        <style>
        </style>

        <div style="margin: 10px;">
            <table style="height: 40px; ">
                <tbody>
                    <tr>
                        <td style="width: 85px;text-align: left;">納品NO：</td>
                        <td style="width: 260px;">YYYYMMDD-HHMMSS</td>
                        <td style="width: 90px;text-align: left;">納品名称：</td>
                        <td style="width: 180px;">XXXXXXXX</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    
                    </tr>
                </tbody>
            </table>
            <div style="overflow: hidden;">
                <table class="table_detail_header" style="width: 1068px;table-layout: fixed;text-align: center;">
                    <thead>
                        <tr class="header">
                            <th style="width: 90px;">商品管理番号</th>
                            <th style="width: 160px;">分類①</th>
                            <th style="width: 160px;">分類②</th>

                            <th style="width: 120px;">ASIN番号</th>
                            <th style="width: 150px;">SKU番号</th>
                            <th style="width: 120px;">LABEL番号</th>

                            <th style="width: 80px;">FBA数量</th>
                            <th style="width: 80px;">LOCAL数量</th>
                            <th style="width: 80px;">納品数量</th>
                        </tr>
                    </thead>
                </table>

            </div>
            <div style="overflow-x: hidden;height: 500px; overflow-y: auto;">
                <table class=" table_detail_content" style="width: 1068px;table-layout: fixed;text-align: center;">
                    <tbody>
                        <tr>
                            <td style="width: 90px;">P002</td>
                            <td style="width: 160px;">XXXXXXX</td>
                            <td style="width: 160px;">XXXXXXX</td>

                            <td style="width: 120px;">XXXXXXX</td>
                            <td style="width: 150px;">XXXXXXX</td>
                            <td style="width: 120px;">XXXXXXX</td>

                            <td style="width: 80px;">XXXXXXX</td>
                            <td style="width: 80px;">XXXXXXX</td>
                            <td style="width: 80px;">XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                        <tr>
                            <td>P002</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                            <td>XXXXXXX</td>
                        </tr>
                    </tbody>
                </table>

            </div>

        </div>
    </div>