create table public."IPT_ビジネスレポート-3" (
  "日付" character varying(20)
  , "注文商品売上" character varying(20)
  , "注文商品売上-B2B" character varying(20)
  , "注文された商品点数" character varying(20)
  , "注文された商品点数 - B2B" character varying(20)
  , "注文品目総数" character varying(20)
  , "注文品目総数 - B2B" character varying(20)
  , "ページビュー - 合計" character varying(20)
  , "ページビュー数-合計-B2B" character varying(20)
  , "セッション - 合計" character varying(20)
  , "セッション-合計-B2B" character varying(20)
  , "おすすめ商品(ショッピングカートボックス)1の" character varying(20)
  , "おすすめ商品(ショッピングカートボックス)2の" character varying(20)
  , "ユニットセッション率" character varying(20)
  , "ユニットセッション率 - B2B" character varying(20)
  , "平均出品数" character varying(20)
  , "親商品の平均" character varying(20)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);