create table public."IPT_ビジネスレポート-2" (
  "日付" character varying(20)
  , "注文商品売上" character varying(20)
  , "注文商品売上-B2B" character varying(20)
  , "注文された商品点数" character varying(20)
  , "注文された商品点数 - B2B" character varying(20)
  , "注文品目総数" character varying(20)
  , "注文品目総数 - B2B" character varying(20)
  , "返金されたユニット" character varying(20)
  , "返金率" character varying(20)
  , "受け取った評価" character varying(20)
  , "受け取った低評価" character varying(20)
  , "受け取った低評価の割合" character varying(20)
  , "承認済みのAmazonマーケットプレイス保証申請" character varying(20)
  , "請求額" character varying(20)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);