drop table public."ZZZ_INPUT_売上詳細情報";

create table public."ZZZ_INPUT_売上詳細情報" (
  "日付時間" character varying(50)
  , "決済番号" character varying(20)
  , "トランザクションの種類" character varying(50)
  , "注文番号" character varying(50)
  , "SKU" character varying(20)
  , "説明" character varying(500)
  , "数量" character varying(20)
  , "Amazon出品サービス" character varying(50)
  , "フルフィルメント" character varying(20)
  , "市町村" character varying(50)
  , "都道府県" character varying(50)
  , "郵便番号" character varying(20)
  , "税金徴収型" character varying(40)
  , "商品売上" character varying(20)
  , "商品の売上税" character varying(20)
  , "配送料" character varying(20)
  , "配送料の税金" character varying(20)
  , "ギフト包装手数料" character varying(20)
  , "ギフト包装クレジットの税金" character varying(20)
  , "Amazonポイントの費用" character varying(20)
  , "プロモーション割引額" character varying(20)
  , "プロモーション割引の税金" character varying(20)
  , "源泉徴収税を伴うマーケットプレイス" character varying(20)
  , "手数料" character varying(20)
  , "FBA 手数料" character varying(20)
  , "トランザクションに関するその他の手数料" character varying(20)
  , "その他" character varying(20)
  , "合計" character varying(20)
  , "FLG" character varying(1)
);
