drop table public."ZZZ_INPUT_”­‘—î•ñ_AMAZON";

create table public."ZZZ_INPUT_”­‘—î•ñ_AMAZON" (
  "”­‘—ó‘Ô" character varying(20)
  , "’•¶”Ô†" character varying(50)
  , "’•¶€–Ú”Ô†" character varying(20)
  , "’•¶ŠÔ" character varying(50)
  , "x•¥ŠÔ" character varying(50)
  , "ƒŒƒ|[ƒgŠÔ" character varying(50)
  , "”­‘—ŠúŒÀ" character varying(50)
  , "c‚è“ú”" character varying(10)
  , "w“üÒƒ[ƒ‹" character varying(50)
  , "w“üÒ–¼Ì" character varying(50)
  , "w“üÒ“d˜b”Ô†" character varying(50)
  , "SKU”Ô†" character varying(50)
  , "¤•i–¼Ì" character varying(500)
  , "¤•i”—Ê" character varying(10)
  , "”­‘—Ï”—Ê" character varying(10)
  , "–¢”­‘—”—Ê" character varying(10)
  , "”­‘—ƒŒƒxƒ‹" character varying(20)
  , "ˆ¶æ–¼Ì" character varying(50)
  , "ˆ¶æZŠ‚P" character varying(200)
  , "ˆ¶æZŠ‚Q" character varying(200)
  , "ˆ¶æZŠ‚R" character varying(200)
  , "ˆ¶æZŠs" character varying(50)
  , "ˆ¶æ“s“¹•{Œ§" character varying(20)
  , "ˆ¶æ—X•Ö”Ô†" character varying(20)
  , "ˆ¶æ‘" character varying(10)
);
