drop table public."HIS_ペイメント情報";

create table public."HIS_ペイメント情報" (
  "日付/時間" character varying(50)
  , "決済番号" character varying(50)
  , "トランザクションの種類" character varying(50)
  , "注文番号" character varying(50)
  , "SKU" character varying(50)
  , "説明" character varying(200)
  , "数量" character varying(50)
  , "Amazon 出品サービス" character varying(50)
  , "フルフィルメント" character varying(50)
  , "市町村" character varying(50)
  , "都道府県" character varying(50)
  , "郵便番号" character varying(50)
  , "税金徴収型" character varying(50)
  , "商品売上" character varying(50)
  , "商品の売上税" character varying(50)
  , "配送料" character varying(50)
  , "配送料の税金" character varying(50)
  , "ギフト包装手数料" character varying(50)
  , "ギフト包装クレジットの税金" character varying(50)
  , "Amazonポイントの費用" character varying(50)
  , "プロモーション割引額" character varying(50)
  , "プロモーション割引の税金" character varying(50)
  , "源泉徴収税を伴うマーケットプレイス" character varying(50)
  , "手数料" character varying(50)
  , "FBA 手数料" character varying(50)
  , "トランザクションに関するその他の手数料" character varying(50)
  , "その他" character varying(50)
  , "合計" character varying(50)
  , "店舗ID" character varying(50)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);