drop table public."IPT_ビジネスレポート-4";

create table public."IPT_ビジネスレポート-4" (
  "(親) ASIN" character varying(50)
  , "(子) ASIN" character varying(50)
  , "タイトル" character varying(500)
  , "SKU" character varying(50)
  , "セッション - 合計" character varying(50)
  , "セッション-合計-B2B" character varying(50)
  , "セッション率 - 合計" character varying(50)
  , "セッション率 - 合計ーB2B" character varying(50)
  , "ページビュー - 合計" character varying(50)
  , "ページビュー数-合計-B2B" character varying(50)
  , "ページビュー率 - 合計" character varying(50)
  , "ページビュー率 - 合計‐B2B" character varying(50)
  , "おすすめ商品(カートボックス)の割合" character varying(50)
  , "おすすめ商品(カートボックス)の割合 - B2B" character varying(50)
  , "注文された商品点数" character varying(50)
  , "注文された商品点数 - B2B" character varying(50)
  , "ユニットセッション率" character varying(50)
  , "ユニットセッション率 - B2B" character varying(50)
  , "注文商品売上" character varying(50)
  , "注文商品売上-B2B" character varying(50)
  , "注文品目総数" character varying(50)
  , "注文品目総数 - B2B" character varying(50)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);