drop table public."IPT_FBA在庫出荷情報";

create table public."IPT_FBA在庫出荷情報" (
  "Amazon注文番号" character varying(50)
  , "出品者注文ID" character varying(50)
  , "納品番号" character varying(50)
  , "出荷商品ID" character varying(50)
  , "Amazon注文商品ID" character varying(50)
  , "出品者注文商品ID" character varying(50)
  , "注文受付日" character varying(50)
  , "支払日" character varying(50)
  , "発送日" character varying(50)
  , "レポート完了日" character varying(50)
  , "購入者のEメール" character varying(50)
  , "購入者名" character varying(50)
  , "購入者の電話番号" character varying(50)
  , "出品者SKU" character varying(50)
  , "商品名" character varying(100)
  , "出荷商品数" character varying(50)
  , "通貨" character varying(50)
  , "商品価格" character varying(50)
  , "商品税額" character varying(50)
  , "配送料" character varying(50)
  , "配送料税額" character varying(50)
  , "ギフト包装料" character varying(50)
  , "ギフト包装料税額" character varying(50)
  , "配送サービスレベル" character varying(50)
  , "受取人" character varying(50)
  , "お届け先1" character varying(50)
  , "お届け先2" character varying(50)
  , "お届け先3" character varying(50)
  , "市区町村" character varying(50)
  , "都道府県" character varying(50)
  , "発送先郵便番号" character varying(50)
  , "国" character varying(50)
  , "お届け先電話番号" character varying(50)
  , "請求先の住所1" character varying(50)
  , "請求先の住所2" character varying(50)
  , "請求先の住所3" character varying(50)
  , "請求先の市区町村" character varying(50)
  , "請求先の都道府県" character varying(50)
  , "請求先の郵便番号" character varying(50)
  , "請求先の国" character varying(50)
  , "商品プロモーション割引" character varying(50)
  , "配送プロモーション割引" character varying(50)
  , "配送業者" character varying(50)
  , "問い合わせ番号" character varying(50)
  , "配送予定日" character varying(50)
  , "FC" character varying(50)
  , "出荷経路" character varying(50)
  , "販売経路" character varying(50)
  , "付与されたAmazon ポイント" character varying(50)
  , "店舗ID" character varying(50)
  , "登録日時" character varying(50)
  , "更新日時" character varying(50)
);