drop table public."IPT_全出品情報";

create table public."IPT_全出品情報" (
  "出品者SKU" character varying(50)
  , "ASIN 1" character varying(50)
  , "商品名" character varying(500)
  , "商品の説明" character varying(2000)
  , "出品ID" character varying(50)
  , "価格" character varying(50)
  , "数量" character varying(50)
  , "出品日" character varying(50)
  , "商品IDタイプ" character varying(50)
  , "コンディション説明" character varying(50)
  , "コンディション" character varying(50)
  , "国外へ配送可" character varying(50)
  , "迅速な配送" character varying(50)
  , "商品ID" character varying(50)
  , "在庫数" character varying(50)
  , "フルフィルメントチャンネル" character varying(50)
  , "法人価格" character varying(50)
  , "数量割引のタイプ" character varying(50)
  , "数量の下限1" character varying(50)
  , "数量割引1" character varying(50)
  , "数量の下限2" character varying(50)
  , "数量割引2" character varying(50)
  , "数量の下限3" character varying(50)
  , "数量割引3" character varying(50)
  , "数量の下限4" character varying(50)
  , "数量割引4" character varying(50)
  , "数量の下限5" character varying(50)
  , "数量割引5" character varying(50)
  , "使用しない支払い方法" character varying(50)
  , "配送日時指定SKUリスト" character varying(50)
  , "merchant-shipping-group" character varying(50)
  , "ポイント" character varying(50)
  , "商品税コード" character varying(50)
  , "ステータス" character varying(50)
  , "出品価格の下限" character varying(50)
  , "出品価格の上限" character varying(50)
  , "累積購入割引価格タイプ" character varying(50)
  , "累積購入割引下限1" character varying(50)
  , "累積購入割引価格1" character varying(50)
  , "累積購入割引下限2" character varying(50)
  , "累積購入割引価格2" character varying(50)
  , "累積購入割引下限3" character varying(50)
  , "累積購入割引価格3" character varying(50)
  , "調達タイプ" character varying(50)
  , "店舗ID" character varying(50)
  , "登録日時" character varying(50)
  , "更新日時" character varying(50)
);